# Template from https://docs.dockstore.org/en/stable/getting-started/github-apps/github-apps.html
version: 1.2
workflows:
  - name: Cellranger
    subclass: WDL
    publish: true
    primaryDescriptorPath: /workflows/cellranger/cellranger_workflow.wdl
    testParameterFiles:
      - /test/dummy.json
    authors:
      - name: Cumulus Team
        email: cumulus-support@googlegroups.com
        affiliation: Genentech
  - name: CellBender
    subclass: WDL
    publish: true
    primaryDescriptorPath: /workflows/cellbender/cellbender.wdl
    testParameterFiles:
      - /test/dummy.json
    authors:
      - name: Cumulus Team
        email: cumulus-support@googlegroups.com
        affiliation: Genentech
    filters:
      tags:
        - /.*/
      branches:
        - master
